web_extra_exposed_ports:
  - name: websocket
    container_port: 8080
    http_port: 8081
    https_port: 8080

web_extra_daemons:
  - name: websocket
    command: "node SocketServer.js"
    directory: /opt/ddev-websocket
